site_name: Modpack Wiki
site_description: Guides and one-line summaries for a 1.20.1 Forge modpack
site_url: https://example.com
use_directory_urls: true
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - search.suggest
    - search.highlight
    - content.code.copy
plugins:
  - search
nav:
  - Home: index.md
  - Guides:
      - 주요 모드 가이드: guides/featured-mods.md
  - Mods by Category:
      - Worldgen: categories/worldgen.md
      - Mobs: categories/mobs.md
      - QoL / UI: categories/qol-ui.md
      - Performance: categories/performance.md
      - Libraries: categories/libraries.md
      - Create / Industry: categories/create-industry.md
      - Food / FD add-ons: categories/food-fd-add-ons.md
      - Villagers & Economy: categories/villagers-economy.md
markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true
  - def_list
  - attr_list
# If you later want manual ordering, add a 'nav:' section here.
