site_name: Modpack Wiki
site_description: Guides and one-line summaries for a 1.20.1 Forge modpack
site_url: https://example.com
use_directory_urls: true
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - search.suggest
    - search.highlight
    - content.code.copy
plugins:
  - search
nav:
  - Home: index.md
  - Mods by Category:
      - Worldgen: index.md#worldgen
      - Mobs: index.md#mobs
      - QoL / UI: index.md#qol-ui
      - Performance: index.md#performance
      - Libraries: index.md#libraries
      - Create / Industry: index.md#create-industry
      - Food / FD add-ons: index.md#food-fd-add-ons
      - Villagers & Economy: index.md#villagers-economy
markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true
  - def_list
  - attr_list
# If you later want manual ordering, add a 'nav:' section here.
